// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xybagseygjimzzuasvbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5YmFnc2V5Z2ppbXp6dWFzdmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTM0MzgsImV4cCI6MjA3MjUyOTQzOH0.5p5MGpvcb0ShMEKznNWTSySqehzm5_4S8iHINO2FhlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});